#!/usr/bin/bash
. "${HOME}/.cache/wal/colors.sh"
[ $( echo -e "No\nYes" | dmenu -fn JetBrainsMonoNerdFont -nb $color0 -nf $color7 -sb $color7 -sf $color0 -i -l 10 -p "Do you want to shutdown?") == "Yes" ] && systemctl poweroff